# specify which database and adapter to use for which environment

development:
  adapter: sqlite3
  database: db/horse-development

test:
  adapter: sqlite3
  database: db/horse-test

production:
  adapter: sqlite3
  database: db/horse-production
